train:
  device: cuda:0
  lr: 3e-2
  num_epochs: 1
  train_batch_size: 16

eval:
  device: "cuda:0"
  eval_batch_size: 8
  eval_model_path: "./res/models/glue_bigscience_bloomz-560m_0.2_1"
  eval_base: False

model:
  model_name: "bigscience/bloomz-560m"
  tokenizer_name: "bigscience/bloomz-560m"
  max_length: 64

peft:
  task_type: "CAUSAL_LM"
  num_virtual_tokens: 8
  prompt_init_text: "Classify if the sentence is positive or negative:"

dataset:
  dataset_name: "glue"
  task_name: "sst2"
  train_ratio: 0.2