train:
  device: cuda:0
  lr: 3e-2
  num_epochs: 5
  train_batch_size: 16

eval:
  device: "cuda:0"
  eval_batch_size: 8
  eval_model_path: "./res/models/poli_bigscience_bloomz-560m_1_5"
  eval_base: False

model:
  model_name: "bigscience/bloomz-560m"
  tokenizer_name: "bigscience/bloomz-560m"
  max_length: 70

peft:
  task_type: "CAUSAL_LM"
  num_virtual_tokens: 15
  prompt_init_text: "Classify if the predicted subreddit of this sentence is 0, 2 or 3:"

dataset:
  dataset_path: "./data/guns/supervised_dataset/0.0.6/exp1_2_2_6/comments_guns_with_scores_above_quantile_0.90_train_64.json"
  eval_dataset_path: "./data/guns/supervised_dataset/0.0.6/exp1_2_2_6/comments_guns_with_scores_above_quantile_0.90_val_64.json"
  test_dataset_path: "./data/guns/supervised_dataset/0.0.6/exp1_2_2_6/comments_guns_with_scores_above_quantile_0.90_val_64.json"
  train_ratio: 1